### ISSUE TITLE
Add support for continuation frames

### ISSUE THREAD

**Issue by d6y** [http4s/http4s-websocket#1]
The project does not currently support the web socket "continuation" opcode (as described in [RFC6455](https://tools.ietf.org/html/rfc6455)).  

If  a continuation frame is received the result will be:

``` scala
Scala.MatchError: 0 (of class java.lang.Integer)
    at org.http4s.websocket.WebsocketBits$.makeFrame
```

@bryce-anderson notes that we probably need something like...

``` scala
case WebsocketBits.CONTINUATION => Continuation(data, last)
```

...around about [here](https://github.com/http4s/http4s-websocket/blob/f1d77fd5d12d4dbed6e16486863fc75b3a502c9e/src/main/scala/org/http4s/websocket/WebsocketBits.scala#L30).

**Comment by bryce-anderson** [comment]
Closed via a6beead12156679bac5c859a3ecde9bd3cadf84c.
