### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by kevinmeredith** [http4s/http4s-websocket#5]
Hi - 

Could you please recommend any examples of how to use this library as either a client or server?

Thanks,
Kevin

**Comment by rossabaker** [comment]
This library is a support module for raw blaze and http4s and not really intended to be used standalone.  See the [BlazeWebSocketExample](https://github.com/http4s/http4s/blob/5865af256e73339a9ff96b119749e7a231a374bf/examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala).
