### ISSUE TITLE
Add convience constructor for Close frame

### ISSUE THREAD

**Issue by keirlawson** [http4s/http4s-websocket#8]
Per discussion in the http4s gitter channel, it would be great to have an easier way to set the close code when ending the websocket connection from the server as presently if the code is to be stored as a human readable decimal (say `1000`) it must then be manually converted to an unsigned short in byte array form for use with the existing `Close(data: Array[Byte])` constructor.  

I was about to start working on a PR for this however I'm not sure what form an alternate constructor should take.  Specifically, should the returned `Close` be wrapped in an `Either` so that in the case that the parameter is not one of the pre-defined control codes (which seem to range from 1000 to 4999) we can pass back an error to the caller? Also given that by my reading of the spec the code _should_ never be greater than 4999 even though it is represented as a 16 bit unsigned int, would `short` be an appropriate parameter type for this code, along with an optional `String` for the reason?

**Comment by rossabaker** [comment]
The idiom in http4s is to return an `Either[ParseError, A]`, but you don't have a `ParseError` down here.  And `ParseError` implies coming from a `String`.  I could imagine:

```scala
class InvalidCloseCodeException(i: Int) extends RuntimeException

object Close {
  def fromInt(i: Int): Either[InvalidCloseCodeException, Close]
}
```

`Short` literals are a pain, and the domain still doesn't line up, so I probably wouldn't bother with that.

I'm not too familiar with the spec, but I'm wondering why the Close frame isn't modeled as a code and a reason, and then knows how to serialize/deserialize itself.  It seems like neither an arbitrary byte array nor an arbitrary `(Int, String)` are legal close frames, so there's that validation to deal with either way.
